### PR TITLE
Add Shinobu and Megumin command

### PR DESCRIPTION
**Pull request by Prie-st**

### CODE REVIEW

**Review by crazygmr101 — CHANGES_REQUESTED** [review]
test it :threat:

**Comment by AlaRubra123** [comment]
Just merge the untested code. What's the worst that could happen?

**Comment by crazygmr101** [comment]
> Just merge the untested code. What's the worst that could happen?

i have *standards*

**Comment by AlaRubra123** [comment]
> > Just merge the untested code. What's the worst that could happen?
> 
> i have _standards_

Nah. It's coo.

**Review by crazygmr101 — APPROVED** [review]

**Pull request closed without merging**
